### ISSUE TITLE
Excessive Logging

### ISSUE THREAD

**Issue by ogrady** [ogrady/Botgart#60]

**Comment by ogrady** [comment]
New logging method has been introduced to specify a logging level and give some proper context in https://github.com/ogrady/ts-gw2-verifyBot/commit/04cd9141ebca9cf09f08938832fe2fad72c77a66

See https://github.com/ogrady/ts-gw2-verifyBot/commit/11d6114d5de1ed89d29691e997274231baa8fae4 to learn about the usage

@Jeybla you can now introduce as much additional logging as needed.

**Comment by ogrady** [comment]
As of https://github.com/ogrady/Botgart/commit/90bd8c0c3bade4221284460442b73ba610f742ee logging doesn't have explicit labeling anymore. Labeling was used to specify where the logging was called from. This is now automatically done by inspecting the call stack.

```javascript
Util.log("error", "MyFile.js", "something went wrong");
```

is now 

```javascript
Util.log("error", "something went wrong");
```

but produces the same output, assuming the statement was issued from the file `MyFile.js`.

**Comment by Jeybla** [comment]
Since we are also capturing all the TS3Bot output by now, the logging seems fine to me for now.
